[workspace]
members = [
	"codegen",
	"codegen-macro",
	"codegen-impl",
	"example-build",
	"example-macro",
	"rustfmt-wrapper"
]

default-members = [
	"codegen",
	"codegen-macro",
	"codegen-impl",
	"rustfmt-wrapper"
]